import 'package:fast_ai/widgets/app_bar/custom_app_bar.dart';import 'package:fast_ai/widgets/app_bar/appbar_leading_iconbutton.dart';import 'package:flutter/material.dart';import 'package:fast_ai/core/app_export.dart';import 'controller/language_settings_controller.dart';// ignore_for_file: must_be_immutable
class LanguageSettingsScreen extends GetWidget<LanguageSettingsController> {const LanguageSettingsScreen({Key? key}) : super(key: key, );

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(body: SizedBox(width: double.maxFinite, child: Column(children: [SizedBox(height: 20.v), Card(clipBehavior: Clip.antiAlias, elevation: 0, color: theme.colorScheme.onErrorContainer, shape: RoundedRectangleBorder(borderRadius: BorderRadiusStyle.roundedBorder40, ), child: Container(height: 792.v, width: double.maxFinite, padding: EdgeInsets.all(30.h), decoration: AppDecoration.fillOnErrorContainer.copyWith(borderRadius: BorderRadiusStyle.roundedBorder40, ), child: Stack(alignment: Alignment.topCenter, children: [_buildArabic(), Align(alignment: Alignment.topCenter, child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, children: [_buildAppBar(), SizedBox(height: 21.v), Text("lbl_language".tr.toUpperCase(), style: theme.textTheme.displayMedium, ), SizedBox(height: 24.v), _buildFrameThirtySix(bangla: "lbl_arabic".tr, ), SizedBox(height: 20.v), Divider(), SizedBox(height: 19.v), _buildFrameThirtySix(bangla: "lbl_bangla".tr, ), SizedBox(height: 20.v), Divider(), SizedBox(height: 19.v), _buildFrameThirtySix3(), SizedBox(height: 20.v), Divider(), SizedBox(height: 19.v), _buildFrameThirtySix(bangla: "lbl_japanese".tr, ), SizedBox(height: 20.v), Divider(), SizedBox(height: 19.v), _buildFrameThirtySix(bangla: "lbl_russian".tr, ), SizedBox(height: 20.v), Divider(), SizedBox(height: 19.v), _buildFrameThirtySix(bangla: "lbl_brazilian".tr, ), SizedBox(height: 20.v), Divider()], ), )], ), ), )], ), ), ), ); } 
/// Section Widget
Widget _buildArabic() { return Align(alignment: Alignment.bottomCenter, child: Padding(padding: EdgeInsets.only(bottom: 53.v), child: Column(mainAxisSize: MainAxisSize.min, children: [Row(mainAxisAlignment: MainAxisAlignment.center, children: [Container(height: 50.adaptSize, width: 50.adaptSize, decoration: BoxDecoration(color: appTheme.blueGray100, borderRadius: BorderRadius.circular(25.h, ), ), ), Padding(padding: EdgeInsets.only(left: 20.h, top: 3.v, bottom: 7.v, ), child: Text("lbl_brazilian".tr, style: CustomTextStyles.headlineLargeBlack90003, ), ), Container(margin: EdgeInsets.only(left: 113.h, top: 10.v, bottom: 10.v, ), padding: EdgeInsets.all(9.h), decoration: AppDecoration.fillGray5001.copyWith(borderRadius: BorderRadiusStyle.roundedBorder17, ), child: Container(height: 12.adaptSize, width: 12.adaptSize, decoration: BoxDecoration(color: theme.colorScheme.primary, borderRadius: BorderRadius.circular(6.h, ), ), ), )], ), SizedBox(height: 20.v), Divider(color: appTheme.indigo50, )], ), ), ); } 
/// Section Widget
PreferredSizeWidget _buildAppBar() { return CustomAppBar(leadingWidth: double.maxFinite, leading: AppbarLeadingIconbutton(imagePath: ImageConstant.imgArrowLeft, margin: EdgeInsets.only(left: 30.h, right: 295.h, ), onTap: () {onTapArrowLeft();}, ), ); } 
/// Section Widget
Widget _buildFrameThirtySix3() { return Row(children: [CustomImageView(imagePath: ImageConstant.imgEllipse261, height: 50.adaptSize, width: 50.adaptSize, radius: BorderRadius.circular(25.h, ), ), Padding(padding: EdgeInsets.only(left: 20.h, top: 6.v, bottom: 4.v, ), child: Text("lbl_english".tr, style: CustomTextStyles.headlineLargeSemiBold, ), ), Container(margin: EdgeInsets.only(left: 130.h, top: 10.v, bottom: 10.v, ), padding: EdgeInsets.all(9.h), decoration: AppDecoration.fillOnSecondaryContainer.copyWith(borderRadius: BorderRadiusStyle.roundedBorder17, ), child: Container(height: 12.adaptSize, width: 12.adaptSize, decoration: BoxDecoration(color: theme.colorScheme.primary, borderRadius: BorderRadius.circular(6.h, ), ), ), )], ); } 
/// Common widget
Widget _buildFrameThirtySix({required String bangla}) { return Row(children: [CustomImageView(imagePath: ImageConstant.imgEllipse2650x50, height: 50.adaptSize, width: 50.adaptSize, radius: BorderRadius.circular(25.h, ), ), Padding(padding: EdgeInsets.only(left: 20.h, top: 6.v, bottom: 4.v, ), child: Text(bangla, style: CustomTextStyles.headlineLargeSemiBold.copyWith(color: appTheme.whiteA700, ), ), ), CustomImageView(imagePath: ImageConstant.imgPlay, height: 30.adaptSize, width: 30.adaptSize, margin: EdgeInsets.only(left: 132.h, top: 10.v, bottom: 10.v, ), )], ); } 

/// Navigates to the previous screen.
onTapArrowLeft() { Get.back(); } 
 }
