import 'package:fast_ai/widgets/app_bar/custom_app_bar.dart';import 'package:fast_ai/widgets/app_bar/appbar_leading_iconbutton.dart';import 'package:fast_ai/widgets/custom_switch.dart';import 'package:flutter/material.dart';import 'package:fast_ai/core/app_export.dart';import 'controller/notification_settings_controller.dart';// ignore_for_file: must_be_immutable
class NotificationSettingsScreen extends GetWidget<NotificationSettingsController> {const NotificationSettingsScreen({Key? key}) : super(key: key, );

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(body: SizedBox(width: double.maxFinite, child: Column(children: [SizedBox(height: 20.v), Container(padding: EdgeInsets.symmetric(vertical: 30.v), decoration: AppDecoration.fillOnErrorContainer.copyWith(borderRadius: BorderRadiusStyle.roundedBorder40, ), child: Column(mainAxisSize: MainAxisSize.min, children: [_buildAppBar(), SizedBox(height: 21.v), Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(left: 30.h), child: Text("lbl_notifications".tr.toUpperCase(), style: theme.textTheme.displayMedium, ), ), ), SizedBox(height: 15.v), _buildAll(), SizedBox(height: 14.v), Divider(indent: 30.h, endIndent: 30.h, ), SizedBox(height: 10.v), _buildAll1(), SizedBox(height: 14.v), Divider(indent: 30.h, endIndent: 30.h, ), SizedBox(height: 14.v)], ), )], ), ), ), ); } 
/// Section Widget
PreferredSizeWidget _buildAppBar() { return CustomAppBar(leadingWidth: double.maxFinite, leading: AppbarLeadingIconbutton(imagePath: ImageConstant.imgArrowLeft, margin: EdgeInsets.only(left: 30.h, right: 295.h, ), onTap: () {onTapArrowLeft();}, ), ); } 
/// Section Widget
Widget _buildAll() { return Padding(padding: EdgeInsets.symmetric(horizontal: 30.h), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("msg_email_notifications".tr, style: theme.textTheme.headlineSmall, ), SizedBox(height: 3.v), SizedBox(width: 185.h, child: Text("msg_change_the_email".tr, maxLines: 2, overflow: TextOverflow.ellipsis, style: theme.textTheme.labelLarge!.copyWith(height: 1.50, ), ), )], ), Obx(() => CustomSwitch(margin: EdgeInsets.only(top: 22.v, bottom: 19.v, ), value: controller.isSelectedSwitch.value, onChange: (value) {controller.isSelectedSwitch.value = value;}, ), )], ), ); } 
/// Section Widget
Widget _buildAll1() { return Padding(padding: EdgeInsets.symmetric(horizontal: 30.h), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Column(children: [Text("msg_phone_notifications".tr, style: theme.textTheme.headlineSmall, ), SizedBox(height: 3.v), SizedBox(width: 185.h, child: Text("msg_change_the_email".tr, maxLines: 2, overflow: TextOverflow.ellipsis, style: theme.textTheme.labelLarge!.copyWith(height: 1.50, ), ), )], ), Obx(() => CustomSwitch(margin: EdgeInsets.only(top: 22.v, bottom: 19.v, ), value: controller.isSelectedSwitch1.value, onChange: (value) {controller.isSelectedSwitch1.value = value;}, ), )], ), ); } 

/// Navigates to the previous screen.
onTapArrowLeft() { Get.back(); } 
 }
