import 'package:fast_ai/widgets/app_bar/custom_app_bar.dart';import 'package:fast_ai/widgets/app_bar/appbar_leading_iconbutton.dart';import 'package:flutter/material.dart';import 'package:fast_ai/core/app_export.dart';import 'controller/settings_controller.dart';// ignore_for_file: must_be_immutable
class SettingsScreen extends GetWidget<SettingsController> {const SettingsScreen({Key? key}) : super(key: key, );

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(body: SizedBox(width: double.maxFinite, child: Column(children: [SizedBox(height: 20.v), Container(padding: EdgeInsets.symmetric(vertical: 30.v), decoration: AppDecoration.fillOnErrorContainer.copyWith(borderRadius: BorderRadiusStyle.roundedBorder40, ), child: Column(mainAxisSize: MainAxisSize.min, children: [_buildAppBar(), SizedBox(height: 21.v), Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(left: 30.h), child: Text("lbl_app_settings".tr.toUpperCase(), style: theme.textTheme.displayMedium, ), ), ), SizedBox(height: 15.v), _buildAll(), SizedBox(height: 18.v), Divider(indent: 30.h, endIndent: 30.h, ), SizedBox(height: 16.v), _buildAll1(), SizedBox(height: 18.v), Divider(indent: 30.h, endIndent: 30.h, ), SizedBox(height: 15.v), _buildAll2(), SizedBox(height: 18.v), Divider(indent: 30.h, endIndent: 30.h, ), SizedBox(height: 16.v), _buildAll3(), SizedBox(height: 18.v), Divider(indent: 30.h, endIndent: 30.h, ), SizedBox(height: 15.v), _buildAll4(), SizedBox(height: 18.v), Divider(indent: 30.h, endIndent: 30.h, ), SizedBox(height: 77.v)], ), )], ), ), ), ); } 
/// Section Widget
PreferredSizeWidget _buildAppBar() { return CustomAppBar(leadingWidth: double.maxFinite, leading: AppbarLeadingIconbutton(imagePath: ImageConstant.imgArrowLeft, margin: EdgeInsets.only(left: 30.h, right: 295.h, ), onTap: () {onTapArrowLeft();}, ), ); } 
/// Section Widget
Widget _buildAll() { return Padding(padding: EdgeInsets.symmetric(horizontal: 30.h), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_notifications".tr, style: theme.textTheme.headlineSmall, ), SizedBox(height: 3.v), SizedBox(width: 185.h, child: Text("msg_change_the_email".tr, maxLines: 2, overflow: TextOverflow.ellipsis, style: theme.textTheme.labelLarge!.copyWith(height: 1.50, ), ), )], ), CustomImageView(imagePath: ImageConstant.imgArrowRight, height: 22.adaptSize, width: 22.adaptSize, margin: EdgeInsets.only(top: 25.v, bottom: 22.v, ), )], ), ); } 
/// Section Widget
Widget _buildAll1() { return Padding(padding: EdgeInsets.symmetric(horizontal: 30.h), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_language".tr, style: theme.textTheme.headlineSmall, ), SizedBox(width: 191.h, child: Text("msg_change_the_language".tr, maxLines: 2, overflow: TextOverflow.ellipsis, style: theme.textTheme.labelLarge!.copyWith(height: 1.50, ), ), )], ), CustomImageView(imagePath: ImageConstant.imgArrowRight, height: 22.adaptSize, width: 22.adaptSize, margin: EdgeInsets.only(top: 23.v, bottom: 22.v, ), )], ), ); } 
/// Section Widget
Widget _buildAll2() { return Padding(padding: EdgeInsets.symmetric(horizontal: 30.h), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_app_cache".tr, style: theme.textTheme.headlineSmall, ), SizedBox(height: 1.v), SizedBox(width: 209.h, child: Text("msg_you_can_clear_app".tr, maxLines: 2, overflow: TextOverflow.ellipsis, style: theme.textTheme.labelLarge!.copyWith(height: 1.50, ), ), )], ), CustomImageView(imagePath: ImageConstant.imgArrowRight, height: 22.adaptSize, width: 22.adaptSize, margin: EdgeInsets.only(top: 24.v, bottom: 22.v, ), )], ), ); } 
/// Section Widget
Widget _buildAll3() { return Padding(padding: EdgeInsets.symmetric(horizontal: 30.h), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_contact_support".tr, style: theme.textTheme.headlineSmall, ), SizedBox(width: 205.h, child: Text("msg_if_you_have_any".tr, maxLines: 2, overflow: TextOverflow.ellipsis, style: theme.textTheme.labelLarge!.copyWith(height: 1.50, ), ), )], ), CustomImageView(imagePath: ImageConstant.imgArrowRight, height: 22.adaptSize, width: 22.adaptSize, margin: EdgeInsets.only(top: 23.v, bottom: 22.v, ), )], ), ); } 
/// Section Widget
Widget _buildAll4() { return Padding(padding: EdgeInsets.symmetric(horizontal: 30.h), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_version_update".tr, style: theme.textTheme.headlineSmall, ), SizedBox(height: 1.v), SizedBox(width: 204.h, child: Text("msg_make_sure_the_app".tr, maxLines: 2, overflow: TextOverflow.ellipsis, style: theme.textTheme.labelLarge!.copyWith(height: 1.50, ), ), )], ), CustomImageView(imagePath: ImageConstant.imgArrowRight, height: 22.adaptSize, width: 22.adaptSize, margin: EdgeInsets.only(top: 24.v, bottom: 22.v, ), )], ), ); } 

/// Navigates to the previous screen.
onTapArrowLeft() { Get.back(); } 
 }
