import 'package:fast_ai/widgets/app_bar/custom_app_bar.dart';import 'package:fast_ai/widgets/app_bar/appbar_leading_iconbutton_four.dart';import 'package:fast_ai/widgets/app_bar/appbar_trailing_iconbutton_two.dart';import 'package:fast_ai/widgets/custom_drop_down.dart';import 'package:fast_ai/widgets/custom_elevated_button.dart';import 'package:fast_ai/widgets/custom_pin_code_text_field.dart';import 'package:flutter/material.dart';import 'package:fast_ai/core/app_export.dart';import 'controller/change_bg_color_controller.dart';// ignore_for_file: must_be_immutable
class ChangeBgColorScreen extends GetWidget<ChangeBgColorController> {const ChangeBgColorScreen({Key? key}) : super(key: key, );

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, body: SizedBox(width: double.maxFinite, child: Column(children: [SizedBox(height: 20.v), Container(padding: EdgeInsets.symmetric(vertical: 30.v), decoration: AppDecoration.fillPrimaryContainer.copyWith(borderRadius: BorderRadiusStyle.roundedBorder40, ), child: Column(mainAxisSize: MainAxisSize.min, children: [_buildAppBar(), SizedBox(height: 21.v), Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(left: 30.h), child: Text("lbl_fash_vid".tr.toUpperCase(), style: theme.textTheme.displayMedium, ), ), ), Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(left: 30.h), child: Text("msg_convert_text_to2".tr, style: CustomTextStyles.titleLargeGray60002, ), ), ), SizedBox(height: 28.v), CustomImageView(imagePath: ImageConstant.imgRectangle996, height: 200.v, radius: BorderRadius.circular(20.h, ), ), SizedBox(height: 12.v), _buildOptions(), SizedBox(height: 12.v), _buildOtpView1(), SizedBox(height: 80.v), _buildButton()], ), )], ), ), ), ); } 
/// Section Widget
PreferredSizeWidget _buildAppBar() { return CustomAppBar(leadingWidth: 80.h, leading: AppbarLeadingIconbuttonFour(imagePath: ImageConstant.imgArrowLeft, margin: EdgeInsets.only(left: 30.h), onTap: () {onTapArrowLeft();}, ), actions: [AppbarTrailingIconbuttonTwo(imagePath: ImageConstant.imgCut, margin: EdgeInsets.symmetric(horizontal: 30.h), )], ); } 
/// Section Widget
Widget _buildX() { return CustomElevatedButton(height: 50.v, width: 39.h, text: "lbl_1x".tr, margin: EdgeInsets.only(left: 11.h), buttonStyle: CustomButtonStyles.fillGray, ); } 
/// Section Widget
Widget _buildOptions() { return Padding(padding: EdgeInsets.symmetric(horizontal: 30.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [Container(width: 139.h, padding: EdgeInsets.symmetric(horizontal: 16.h, vertical: 9.v, ), decoration: AppDecoration.fillGray90004.copyWith(borderRadius: BorderRadiusStyle.roundedBorder10, ), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, crossAxisAlignment: CrossAxisAlignment.start, children: [Padding(padding: EdgeInsets.only(top: 1.v, bottom: 4.v, ), child: Text("lbl_bg_color".tr, style: theme.textTheme.titleLarge, ), ), CustomImageView(imagePath: ImageConstant.imgEllipse19, height: 30.adaptSize, width: 30.adaptSize, radius: BorderRadius.circular(15.h, ), margin: EdgeInsets.only(bottom: 2.v), )], ), ), Padding(padding: EdgeInsets.only(left: 11.h), child: CustomDropDown(width: 115.h, icon: Container(margin: EdgeInsets.fromLTRB(8.h, 20.v, 18.h, 20.v), child: CustomImageView(imagePath: ImageConstant.imgFavoriteLightGreen80010x12, height: 10.v, ), ), hintText: "lbl_english".tr, items: controller.changeBgColorModelObj.value.dropdownItemList!.value, borderDecoration: DropDownStyleHelper.fillGray, fillColor: appTheme.gray90004, ), ), _buildX()], ), ); } 
/// Section Widget
Widget _buildOtpView() { return Obx(() => CustomPinCodeTextField(context: Get.context!, controller: controller.otpController.value, onChanged: (value) {}, ), ); } 
/// Section Widget
Widget _buildOtpView1() { return SizedBox(height: 138.v, width: 315.h, child: Stack(alignment: Alignment.topLeft, children: [Align(alignment: Alignment.bottomCenter, child: Container(padding: EdgeInsets.symmetric(horizontal: 16.h, vertical: 14.v, ), decoration: AppDecoration.fillBlack90003.copyWith(borderRadius: BorderRadiusStyle.roundedBorder17, ), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, children: [SizedBox(height: 7.v), Container(height: 48.v, width: 258.h, margin: EdgeInsets.only(left: 4.h), child: Stack(alignment: Alignment.bottomRight, children: [Align(alignment: Alignment.center, child: SizedBox(width: 258.h, child: Text("msg_this_is_adom_from".tr, maxLines: 2, overflow: TextOverflow.ellipsis, style: CustomTextStyles.titleMedium16.copyWith(height: 1.50, ), ), ), ), Align(alignment: Alignment.bottomRight, child: Padding(padding: EdgeInsets.only(right: 121.h), child: SizedBox(height: 23.v, child: VerticalDivider(width: 1.h, thickness: 1.v, color: appTheme.black900, endIndent: 3.h, ), ), ), )], ), ), SizedBox(height: 30.v), Align(alignment: Alignment.centerRight, child: Text("msg_12_of_600_characters".tr, style: CustomTextStyles.labelLarge_1, ), )], ), ), ), Align(alignment: Alignment.topLeft, child: Container(margin: EdgeInsets.only(right: 55.h), padding: EdgeInsets.symmetric(horizontal: 20.h, vertical: 13.v, ), decoration: AppDecoration.outlineBlack.copyWith(borderRadius: BorderRadiusStyle.roundedBorder14, ), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, mainAxisAlignment: MainAxisAlignment.center, children: [Text("lbl_change_bg_color".tr, style: theme.textTheme.titleMedium, ), SizedBox(height: 7.v), _buildOtpView(), SizedBox(height: 2.v)], ), ), )], ), ); } 
/// Section Widget
Widget _buildConvert() { return CustomElevatedButton(width: 150.h, text: "lbl_convert".tr, ); } 
/// Section Widget
Widget _buildDownload() { return CustomElevatedButton(width: 150.h, text: "lbl_download".tr, margin: EdgeInsets.only(left: 15.h), buttonStyle: CustomButtonStyles.fillGreenATL15, ); } 
/// Section Widget
Widget _buildButton() { return Padding(padding: EdgeInsets.symmetric(horizontal: 30.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [_buildConvert(), _buildDownload()], ), ); } 

/// Navigates to the previous screen.
onTapArrowLeft() { Get.back(); } 
 }
