import 'package:fast_ai/widgets/app_bar/custom_app_bar.dart';import 'package:fast_ai/widgets/app_bar/appbar_leading_iconbutton.dart';import 'package:flutter/material.dart';import 'package:fast_ai/core/app_export.dart';import 'controller/terms_condition_controller.dart';// ignore_for_file: must_be_immutable
class TermsConditionScreen extends GetWidget<TermsConditionController> {const TermsConditionScreen({Key? key}) : super(key: key, );

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(body: SizedBox(width: double.maxFinite, child: Column(children: [SizedBox(height: 20.v), Container(padding: EdgeInsets.symmetric(vertical: 30.v), decoration: AppDecoration.fillOnErrorContainer.copyWith(borderRadius: BorderRadiusStyle.roundedBorder40, ), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, children: [_buildAppBar(), SizedBox(height: 25.v), Container(width: 208.h, margin: EdgeInsets.only(left: 30.h), child: Text("msg_terms_condition".tr.toUpperCase(), maxLines: 2, overflow: TextOverflow.ellipsis, style: theme.textTheme.displayMedium!.copyWith(height: 1.04, ), ), ), SizedBox(height: 19.v), Padding(padding: EdgeInsets.only(left: 30.h), child: Text("lbl_introduction".tr, style: theme.textTheme.headlineSmall, ), ), SizedBox(height: 11.v), Align(alignment: Alignment.center, child: Container(width: 311.h, margin: EdgeInsets.only(left: 30.h, right: 33.h, ), child: Text("msg_we_at_wasai_llc".tr, maxLines: 11, overflow: TextOverflow.ellipsis, style: theme.textTheme.labelLarge!.copyWith(height: 1.50, ), ), ), ), SizedBox(height: 25.v), Padding(padding: EdgeInsets.only(left: 30.h), child: Text("msg_children_privacy".tr, style: theme.textTheme.headlineSmall, ), ), SizedBox(height: 9.v), Align(alignment: Alignment.center, child: Container(width: 313.h, margin: EdgeInsets.only(left: 30.h, right: 31.h, ), child: RichText(text: TextSpan(children: [TextSpan(text: "msg_lorem_ipsum_does2".tr, style: CustomTextStyles.labelLargeff788495, ), TextSpan(text: "lbl_legal_wasai_co".tr, style: CustomTextStyles.labelLargeff788495, ), TextSpan(text: "msg_if_we_become_aware".tr, style: CustomTextStyles.labelLargeff788495, )], ), textAlign: TextAlign.left, ), ), ), SizedBox(height: 62.v)], ), )], ), ), ), ); } 
/// Section Widget
PreferredSizeWidget _buildAppBar() { return CustomAppBar(leadingWidth: double.maxFinite, leading: AppbarLeadingIconbutton(imagePath: ImageConstant.imgArrowLeft, margin: EdgeInsets.only(left: 30.h, right: 295.h, ), onTap: () {onTapArrowLeft();}, ), ); } 

/// Navigates to the previous screen.
onTapArrowLeft() { Get.back(); } 
 }
