import 'package:fast_ai/widgets/app_bar/custom_app_bar.dart';import 'package:fast_ai/widgets/app_bar/appbar_leading_iconbutton_seven.dart';import 'package:flutter/material.dart';import 'package:fast_ai/core/app_export.dart';import 'controller/my_subscription_controller.dart';// ignore_for_file: must_be_immutable
class MySubscriptionScreen extends GetWidget<MySubscriptionController> {const MySubscriptionScreen({Key? key}) : super(key: key, );

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(backgroundColor: appTheme.gray90002, appBar: _buildAppBar(), body: Container(width: double.maxFinite, padding: EdgeInsets.only(left: 30.h, top: 65.v, right: 30.h, ), child: Column(children: [Container(width: 289.h, margin: EdgeInsets.symmetric(horizontal: 13.h), child: Text("msg_all_of_our_ai_at".tr.toUpperCase(), maxLines: 2, overflow: TextOverflow.ellipsis, textAlign: TextAlign.center, style: theme.textTheme.displaySmall!.copyWith(height: 1.12, ), ), ), SizedBox(height: 1.v), Container(width: 296.h, margin: EdgeInsets.symmetric(horizontal: 9.h), child: Text("msg_you_can_add_more".tr, maxLines: 3, overflow: TextOverflow.ellipsis, textAlign: TextAlign.center, style: CustomTextStyles.titleMediumGray70001.copyWith(height: 1.11, ), ), ), SizedBox(height: 37.v), _buildDays(), SizedBox(height: 47.v), Text("msg_set_up_auto_renew".tr, style: CustomTextStyles.titleMediumPrimary, ), SizedBox(height: 13.v), Text("msg_available_68_days".tr, style: theme.textTheme.headlineMedium, ), Text("msg_adomuihut_gmail_com".tr, style: CustomTextStyles.titleMediumGray700, ), SizedBox(height: 85.v), Text("msg_cancel_subscriptions".tr, style: CustomTextStyles.titleLargeRedA10001, ), SizedBox(height: 5.v)], ), ), ), ); } 
/// Section Widget
PreferredSizeWidget _buildAppBar() { return CustomAppBar(height: 103.v, leadingWidth: double.maxFinite, leading: AppbarLeadingIconbuttonSeven(imagePath: ImageConstant.imgArrowLeft, margin: EdgeInsets.fromLTRB(30.h, 3.v, 295.h, 3.v), onTap: () {onTapArrowLeft();}, ), ); } 
/// Section Widget
Widget _buildDays() { return Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Container(width: 97.h, padding: EdgeInsets.symmetric(horizontal: 20.h, vertical: 10.v, ), decoration: AppDecoration.fillGray80001.copyWith(borderRadius: BorderRadiusStyle.roundedBorder14, ), child: Text("lbl_30_days".tr, style: theme.textTheme.titleMedium, ), ), Container(width: 97.h, padding: EdgeInsets.symmetric(horizontal: 20.h, vertical: 10.v, ), decoration: AppDecoration.fillGray80001.copyWith(borderRadius: BorderRadiusStyle.roundedBorder14, ), child: Text("lbl_60_days".tr, style: theme.textTheme.titleMedium, ), ), Container(width: 105.h, padding: EdgeInsets.symmetric(horizontal: 20.h, vertical: 10.v, ), decoration: AppDecoration.fillGray80001.copyWith(borderRadius: BorderRadiusStyle.roundedBorder14, ), child: Text("lbl_365_days".tr, style: theme.textTheme.titleMedium, ), )], ); } 

/// Navigates to the previous screen.
onTapArrowLeft() { Get.back(); } 
 }
