import 'package:fast_ai/widgets/app_bar/custom_app_bar.dart';import 'package:fast_ai/widgets/app_bar/appbar_leading_iconbutton_three.dart';import 'package:fast_ai/widgets/app_bar/appbar_trailing_iconbutton_one.dart';import 'package:fast_ai/widgets/custom_switch.dart';import 'package:flutter/material.dart';import 'package:fast_ai/core/app_export.dart';import 'controller/blog_idea_controller.dart';// ignore_for_file: must_be_immutable
class BlogIdeaScreen extends GetWidget<BlogIdeaController> {const BlogIdeaScreen({Key? key}) : super(key: key, );

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(body: SizedBox(width: double.maxFinite, child: Column(children: [SizedBox(height: 20.v), Expanded(child: SingleChildScrollView(child: SizedBox(height: 807.v, width: double.maxFinite, child: Stack(alignment: Alignment.center, children: [Align(alignment: Alignment.center, child: Container(padding: EdgeInsets.symmetric(horizontal: 23.h, vertical: 338.v, ), decoration: AppDecoration.fillBlack90002.copyWith(borderRadius: BorderRadiusStyle.roundedBorder40, ), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, mainAxisAlignment: MainAxisAlignment.center, children: [SizedBox(height: 65.v), SizedBox(height: 28.v, width: 227.h, child: Stack(alignment: Alignment.centerLeft, children: [Align(alignment: Alignment.bottomCenter, child: Container(height: 20.v, width: 223.h, decoration: BoxDecoration(color: appTheme.greenA70001, ), ), ), Align(alignment: Alignment.centerLeft, child: SizedBox(height: 28.v, width: 7.h, child: Stack(alignment: Alignment.topCenter, children: [Align(alignment: Alignment.bottomCenter, child: SizedBox(height: 23.v, child: VerticalDivider(width: 1.h, thickness: 1.v, color: theme.colorScheme.primary, ), ), ), Align(alignment: Alignment.topCenter, child: Container(height: 7.adaptSize, width: 7.adaptSize, decoration: BoxDecoration(color: theme.colorScheme.primary, borderRadius: BorderRadius.circular(3.h, ), ), ), )], ), ), )], ), ), _buildView()], ), ), ), Align(alignment: Alignment.center, child: Padding(padding: EdgeInsets.symmetric(horizontal: 30.h), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, children: [_buildAppBar(), SizedBox(height: 21.v), Text("lbl_blog_idea".tr.toUpperCase(), style: theme.textTheme.displayMedium, ), Text("msg_you_can_edit_or".tr, style: CustomTextStyles.titleLargeGray60005, ), SizedBox(height: 34.v), Container(width: 264.h, margin: EdgeInsets.only(right: 50.h), child: Text("msg_15_quick_tips_for".tr, maxLines: 2, overflow: TextOverflow.ellipsis, style: theme.textTheme.headlineMedium!.copyWith(height: 1.21, ), ), ), SizedBox(height: 10.v), _buildTwentyFive(), SizedBox(height: 27.v), SizedBox(width: 211.h, child: Text("msg_1_define_your_app_s".tr, maxLines: 2, overflow: TextOverflow.ellipsis, style: theme.textTheme.headlineMedium!.copyWith(height: 1.21, ), ), ), SizedBox(height: 11.v), Container(width: 307.h, margin: EdgeInsets.only(right: 7.h), child: Text("msg_every_successful".tr, maxLines: 8, overflow: TextOverflow.ellipsis, style: CustomTextStyles.titleSmallGray60005.copyWith(height: 1.57, ), ), )], ), ), ), Align(alignment: Alignment.bottomRight, child: Container(height: 7.adaptSize, width: 7.adaptSize, margin: EdgeInsets.only(right: 25.h, bottom: 374.v, ), decoration: BoxDecoration(color: theme.colorScheme.primary, borderRadius: BorderRadius.circular(3.h, ), ), ), )], ), ), ), )], ), ), ), ); } 
/// Section Widget
Widget _buildView() { return Padding(padding: EdgeInsets.only(left: 4.h, right: 5.h, ), child: Row(children: [Container(height: 20.v, width: 319.h, margin: EdgeInsets.only(top: 3.v), decoration: BoxDecoration(color: appTheme.greenA70001, ), ), SizedBox(height: 23.v, child: VerticalDivider(width: 1.h, thickness: 1.v, color: theme.colorScheme.primary, ), )], ), ); } 
/// Section Widget
PreferredSizeWidget _buildAppBar() { return CustomAppBar(leadingWidth: 80.h, leading: AppbarLeadingIconbuttonThree(imagePath: ImageConstant.imgArrowLeft, margin: EdgeInsets.only(left: 30.h), onTap: () {onTapArrowLeft();}, ), actions: [AppbarTrailingIconbuttonOne(imagePath: ImageConstant.imgCut, margin: EdgeInsets.symmetric(horizontal: 30.h), )], ); } 
/// Section Widget
Widget _buildTwentyFive() { return SizedBox(height: 220.v, width: 313.h, child: Stack(alignment: Alignment.bottomCenter, children: [Align(alignment: Alignment.center, child: SizedBox(width: 313.h, child: RichText(text: TextSpan(children: [TextSpan(text: "msg_in_2023_global2".tr, style: CustomTextStyles.titleSmallff728975.copyWith(height: 1.57, ), ), TextSpan(text: "msg_function_can_be".tr, style: CustomTextStyles.titleSmallffffffff.copyWith(height: 1.57, ), ), TextSpan(text: "msg_the_modern_business".tr, style: CustomTextStyles.titleSmallff728975, )], ), textAlign: TextAlign.left, ), ), ), Align(alignment: Alignment.bottomCenter, child: Container(height: 44.v, width: 190.h, margin: EdgeInsets.only(bottom: 16.v), decoration: BoxDecoration(color: appTheme.black900, borderRadius: BorderRadius.circular(14.h, ), boxShadow: [BoxShadow(color: appTheme.black90003.withOpacity(0.12), spreadRadius: 2.h, blurRadius: 2.h, offset: Offset(0, 11, ), )], ), ), ), Align(alignment: Alignment.bottomCenter, child: Padding(padding: EdgeInsets.fromLTRB(83.h, 170.v, 80.h, 26.v), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [Obx(() => CustomSwitch(margin: EdgeInsets.symmetric(vertical: 3.v), value: controller.isSelectedSwitch.value, onChange: (value) {controller.isSelectedSwitch.value = value;}, ), ), Spacer(flex: 50, ), CustomImageView(imagePath: ImageConstant.imgTranslate, height: 24.adaptSize, width: 24.adaptSize, ), Spacer(flex: 50, ), CustomImageView(imagePath: ImageConstant.imgCopy, height: 24.adaptSize, width: 24.adaptSize, )], ), ), )], ), ); } 

/// Navigates to the previous screen.
onTapArrowLeft() { Get.back(); } 
 }
