import 'package:fast_ai/widgets/app_bar/custom_app_bar.dart';import 'package:fast_ai/widgets/app_bar/appbar_leading_iconbutton.dart';import 'package:fast_ai/widgets/custom_pin_code_text_field.dart';import 'package:fast_ai/widgets/custom_elevated_button.dart';import 'package:flutter/material.dart';import 'package:fast_ai/core/app_export.dart';import 'controller/verification_controller.dart';// ignore_for_file: must_be_immutable
class VerificationScreen extends GetWidget<VerificationController> {const VerificationScreen({Key? key}) : super(key: key, );

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, body: SizedBox(width: double.maxFinite, child: Column(children: [SizedBox(height: 20.v), Container(padding: EdgeInsets.symmetric(vertical: 30.v), decoration: AppDecoration.fillOnErrorContainer.copyWith(borderRadius: BorderRadiusStyle.roundedBorder40, ), child: Column(mainAxisSize: MainAxisSize.min, children: [_buildAppBar(), SizedBox(height: 21.v), Text("lbl_verification".tr.toUpperCase(), style: theme.textTheme.displayMedium, ), Text("msg_we_sent_a_code_on".tr, style: CustomTextStyles.titleLargeBluegray400, ), SizedBox(height: 26.v), Padding(padding: EdgeInsets.symmetric(horizontal: 32.h), child: Obx(() => CustomPinCodeTextField(context: Get.context!, controller: controller.otpController.value, onChanged: (value) {}, ), ), ), SizedBox(height: 34.v), RichText(text: TextSpan(children: [TextSpan(text: "lbl_resend_in".tr, style: CustomTextStyles.titleLargeff788495, ), TextSpan(text: "lbl_00_56".tr, style: CustomTextStyles.titleLargeffffffff22, )], ), textAlign: TextAlign.left, ), SizedBox(height: 38.v), CustomElevatedButton(text: "lbl_continue".tr, margin: EdgeInsets.symmetric(horizontal: 30.h), ), SizedBox(height: 38.v)], ), )], ), ), ), ); } 
/// Section Widget
PreferredSizeWidget _buildAppBar() { return CustomAppBar(leadingWidth: double.maxFinite, leading: AppbarLeadingIconbutton(imagePath: ImageConstant.imgArrowLeft, margin: EdgeInsets.only(left: 30.h, right: 295.h, ), onTap: () {onTapArrowLeft();}, ), ); } 

/// Navigates to the previous screen.
onTapArrowLeft() { Get.back(); } 
 }
