import 'package:fast_ai/widgets/app_bar/custom_app_bar.dart';import 'package:fast_ai/widgets/app_bar/appbar_leading_iconbutton_three.dart';import 'package:fast_ai/widgets/app_bar/appbar_trailing_iconbutton_one.dart';import 'widgets/filds_item_widget.dart';import 'models/filds_item_model.dart';import 'package:fast_ai/widgets/custom_elevated_button.dart';import 'package:flutter/material.dart';import 'package:fast_ai/core/app_export.dart';import 'controller/product_description_controller.dart';// ignore_for_file: must_be_immutable
class ProductDescriptionScreen extends GetWidget<ProductDescriptionController> {const ProductDescriptionScreen({Key? key}) : super(key: key, );

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(body: SizedBox(width: double.maxFinite, child: Column(children: [SizedBox(height: 20.v), Expanded(child: Container(padding: EdgeInsets.symmetric(vertical: 30.v), decoration: AppDecoration.fillBlack90002.copyWith(borderRadius: BorderRadiusStyle.roundedBorder40, ), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, children: [_buildAppBar(), SizedBox(height: 25.v), Container(width: 254.h, margin: EdgeInsets.only(left: 30.h), child: Text("msg_03_product_description".tr.toUpperCase(), maxLines: 2, overflow: TextOverflow.ellipsis, style: theme.textTheme.displayMedium!.copyWith(height: 1.04, ), ), ), Padding(padding: EdgeInsets.only(left: 30.h), child: Text("msg_you_can_convert".tr, style: CustomTextStyles.titleLargeGray60005, ), ), SizedBox(height: 26.v), _buildFilds(), Spacer(), CustomElevatedButton(text: "lbl_make_more".tr, margin: EdgeInsets.symmetric(horizontal: 30.h), alignment: Alignment.center, )], ), ), )], ), ), ), ); } 
/// Section Widget
PreferredSizeWidget _buildAppBar() { return CustomAppBar(leadingWidth: 80.h, leading: AppbarLeadingIconbuttonThree(imagePath: ImageConstant.imgArrowLeft, margin: EdgeInsets.only(left: 30.h), onTap: () {onTapArrowLeft();}, ), actions: [AppbarTrailingIconbuttonOne(imagePath: ImageConstant.imgCut, margin: EdgeInsets.symmetric(horizontal: 30.h), )], ); } 
/// Section Widget
Widget _buildFilds() { return Align(alignment: Alignment.center, child: Padding(padding: EdgeInsets.symmetric(horizontal: 30.h), child: Obx(() => ListView.separated(physics: NeverScrollableScrollPhysics(), shrinkWrap: true, separatorBuilder: (context, index) {return SizedBox(height: 20.v, );}, itemCount: controller.productDescriptionModelObj.value.fildsItemList.value.length, itemBuilder: (context, index) {FildsItemModel model = controller.productDescriptionModelObj.value.fildsItemList.value[index]; return FildsItemWidget(model, );}, ), ), ), ); } 

/// Navigates to the previous screen.
onTapArrowLeft() { Get.back(); } 
 }
